const listPaths = [
    {
        municipality:   'Nordreisa',
        area:           'Reisadalen',
        name:           'Gahperus',
        route:          'Gahperus',
        description:    'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro quidem nihil illum officiis asperiores pariatur nobis nostrum! Error quo veniam temporibus tempore quis illum saepe reprehenderit illo ratione accusamus? Expedita!',
        type:           'Enduro',
        grade:          'Advanced',
        length:         '',
        climb:          '',
        climbHeight:    '',
        geojson:        'GEOJSON/Gahperus.geojson',
        startLocation:  '69.5081, 21.3005',
        endLocation:    '69.5408, 21.3293',
        parking:        '69.5394, 21.3321',
        midpoint:       '69.5261, 21.3005',
        zoomLocation:   '69.5247, 21.3136',
        mapZoom:        '9',
        mapZoomStart:   '12',
    },
    {
        municipality:   'Nordreisa',
        area:           'Reisadalen',
        name:           'Punta',
        route:          'Puntadalen',
        description:    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ipsum aspernatur officia, sapiente ad corporis vero vitae ducimus aut earum doloribus ab tempore odit pariatur sit illum cum dolor,<br> repudiandae voluptas, possimus veritatis ipsam exercitationem. Maiores quam mollitia nesciunt obcaecati repellendus. Molestias itaque facere fuga recusandae sint, porro dolores et?',
        type:           'XC',
        grade:          'Beginner',
        length:         '15 km',
        climb:          '15 km',
        climbHeight:    '200m',
        geojson:        'GEOJSON/Punta.geojson',
        startLocation:  '69.4522, 21.4514',
        endLocation:    '69.4978, 21.4321',
        parking:        '69.4975, 21.4341',
        midpoint:       '69.4855, 21.4341',
        zoomLocation:   '69.4845, 21.4231',
        mapZoom:        '9',
        mapZoomStart:   '13',
    },
    {
        municipality:   'Nordreisa',
        area:           'Storvikhalvøya',
        name:           'Reašvárri',
        route:          'Reašvárri',
        description:    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit nostrum eligendi at numquam ratione neque, doloribus veritatis! Excepturi, similique natus.',
        type:           'Enduro',
        grade:          'Expert',
        length:         '',
        climb:          '',
        climbHeight:    '',
        geojson:        'GEOJSON/Reašvárri.geojson',
        startLocation:  '69.8411, 21.1446',
        endLocation:    '69.8496, 21.0864',
        parking:        '69.8411, 21.1446',
        midpoint:       '69.8439, 21.0995',
        zoomLocation:   '69.8439, 21.0995',
        mapZoom:        '10',
        mapZoomStart:   '12',
    },
    
    {
        municipality:   'Nordreisa',
        area:           'Storslett',
        name:           'Nordkjosfjellet',
        route:          'Nordkjosfjellet',
        description:    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias exercitationem ratione rerum blanditiis veritatis ipsum molestiae enim nihil reiciendis est? Voluptatibus ea repellat adipisci placeat sunt temporibus. Molestiae ratione unde quaerat maiores hic qui quos, repellendus optio accusantium ipsum ab, officiis voluptatem. Vero laboriosam dolorem.',
        type:           'Enduro',
        grade:          'Advanced',
        length:         '',
        climb:          '',
        climbHeight:    '',
        geojson:        'GEOJSON/Nordkjosfjellet.geojson',
        startLocation:  '69.8173, 21.0306',
        endLocation:    '69.7931, 21.0519',
        parking:        '69.8411, 21.1446',
        midpoint:       '69.8053, 21.0400',
        zoomLocation:   '69.8053, 21.0400',
        mapZoom:        '9',
        mapZoomStart:   '13',
    },
];

export { listPaths }; // Export listPaths
