const listPaths = [
    {
        municipality:   'Nordreisa',
        area:           'Reisadalen',
        name:           'Gahperus',
        route:          'Linjeveien',
        description:    'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro quidem nihil illum officiis asperiores pariatur nobis nostrum! Error quo veniam temporibus tempore quis illum saepe reprehenderit illo ratione accusamus? Expedita!',
        type:           'Enduro',
        grade:          'Advanced',
        length:         '11 km',
        climb:          '7 km',
        climbHeight:    '550m',
        geojson:        'GEOJSON/Gahperus.geojson',
        startLocation:  '69.5081, 21.3005',
        endLocation:    '69.5408, 21.3293',
        parking:        '69.5394, 21.3321',
        midpoint:       '69.5181, 21.3005',
        zoomLocation:   '69.5247, 21.3136',
        mapZoom:        '10',
        mapZoomStart:   '12',
    },
    {
        municipality:   'Nordreisa',
        area:           'Reisadalen',
        name:           'Punta',
        route:          'Puntadalen',
        description:    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ipsum aspernatur officia, sapiente ad corporis vero vitae ducimus aut earum doloribus ab tempore odit pariatur sit illum cum dolor,<br> repudiandae voluptas, possimus veritatis ipsam exercitationem. Maiores quam mollitia nesciunt obcaecati repellendus. Molestias itaque facere fuga recusandae sint, porro dolores et?',
        type:           'XC',
        grade:          'Beginner',
        length:         '15 km',
        climb:          '15 km',
        geojson:        'GEOJSON/Punta.geojson',
        startLocation:  '69.4522, 21.4514',
        endLocation:    '69.4978, 21.4321',
        parking:        '69.4975, 21.4341',
        midpoint:       '69.4925, 21.4341',
        zoomLocation:   '69.4925, 21.4341',
        mapZoom:        '11',
        mapZoomStart:   '12',
    },
    {
        municipality:   'Nordreisa',
        area:           'Reisadalen',
        name:           'Gahperus',
        route:          'Linjeveien',
        description:    'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro quidem nihil illum officiis asperiores pariatur nobis nostrum! Error quo veniam temporibus tempore quis illum saepe reprehenderit illo ratione accusamus? Expedita!',
        type:           'Enduro',
        grade:          'Advanced',
        length:         '11 km',
        climb:          '7 km',
        climbHeight:    '550m',
        geojson:        'GEOJSON/Gahperus.geojson',
        startLocation:  '69.5081, 21.3005',
        endLocation:    '69.5408, 21.3293',
        parking:        '69.5394, 21.3321',
        midpoint:       '69.5181, 21.3005',
        zoomLocation:   '69.5247, 21.3136',
        mapZoom:        '10',
        mapZoomStart:   '12',
    },
    {
        municipality:   'Nordreisa',
        area:           'Reisadalen',
        name:           'Punta',
        route:          'Puntadalen',
        description:    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ipsum aspernatur officia, sapiente ad corporis vero vitae ducimus aut earum doloribus ab tempore odit pariatur sit illum cum dolor,<br> repudiandae voluptas, possimus veritatis ipsam exercitationem. Maiores quam mollitia nesciunt obcaecati repellendus. Molestias itaque facere fuga recusandae sint, porro dolores et?',
        type:           'XC',
        grade:          'Beginner',
        length:         '15 km',
        climb:          '15 km',
        geojson:        'GEOJSON/Punta.geojson',
        startLocation:  '69.4522, 21.4514',
        endLocation:    '69.4978, 21.4321',
        parking:        '69.4975, 21.4341',
        midpoint:       '69.4925, 21.4341',
        zoomLocation:   '69.4925, 21.4341',
        mapZoom:        '11',
        mapZoomStart:   '12',
    },
    {
        municipality:   'Nordreisa',
        area:           'Reisadalen',
        name:           'Gahperus',
        route:          'Linjeveien',
        description:    'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro quidem nihil illum officiis asperiores pariatur nobis nostrum! Error quo veniam temporibus tempore quis illum saepe reprehenderit illo ratione accusamus? Expedita!',
        type:           'Enduro',
        grade:          'Advanced',
        length:         '11 km',
        climb:          '7 km',
        climbHeight:    '550m',
        geojson:        'GEOJSON/Gahperus.geojson',
        startLocation:  '69.5081, 21.3005',
        endLocation:    '69.5408, 21.3293',
        parking:        '69.5394, 21.3321',
        midpoint:       '69.5181, 21.3005',
        zoomLocation:   '69.5247, 21.3136',
        mapZoom:        '10',
        mapZoomStart:   '12',
    },
    {
        municipality:   'Nordreisa',
        area:           'Reisadalen',
        name:           'Punta',
        route:          'Puntadalen',
        description:    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ipsum aspernatur officia, sapiente ad corporis vero vitae ducimus aut earum doloribus ab tempore odit pariatur sit illum cum dolor,<br> repudiandae voluptas, possimus veritatis ipsam exercitationem. Maiores quam mollitia nesciunt obcaecati repellendus. Molestias itaque facere fuga recusandae sint, porro dolores et?',
        type:           'XC',
        grade:          'Beginner',
        length:         '15 km',
        climb:          '15 km',
        geojson:        'GEOJSON/Punta.geojson',
        startLocation:  '69.4522, 21.4514',
        endLocation:    '69.4978, 21.4321',
        parking:        '69.4975, 21.4341',
        midpoint:       '69.4925, 21.4341',
        zoomLocation:   '69.4925, 21.4341',
        mapZoom:        '11',
        mapZoomStart:   '12',
    },
    {
        municipality:   'Nordreisa',
        area:           'Reisadalen',
        name:           'Gahperus',
        route:          'Linjeveien',
        description:    'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro quidem nihil illum officiis asperiores pariatur nobis nostrum! Error quo veniam temporibus tempore quis illum saepe reprehenderit illo ratione accusamus? Expedita!',
        type:           'Enduro',
        grade:          'Advanced',
        length:         '11 km',
        climb:          '7 km',
        climbHeight:    '550m',
        geojson:        'GEOJSON/Gahperus.geojson',
        startLocation:  '69.5081, 21.3005',
        endLocation:    '69.5408, 21.3293',
        parking:        '69.5394, 21.3321',
        midpoint:       '69.5181, 21.3005',
        zoomLocation:   '69.5247, 21.3136',
        mapZoom:        '10',
        mapZoomStart:   '12',
    },
    {
        municipality:   'Nordreisa',
        area:           'Reisadalen',
        name:           'Punta',
        route:          'Puntadalen',
        description:    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ipsum aspernatur officia, sapiente ad corporis vero vitae ducimus aut earum doloribus ab tempore odit pariatur sit illum cum dolor,<br> repudiandae voluptas, possimus veritatis ipsam exercitationem. Maiores quam mollitia nesciunt obcaecati repellendus. Molestias itaque facere fuga recusandae sint, porro dolores et?',
        type:           'XC',
        grade:          'Beginner',
        length:         '15 km',
        climb:          '15 km',
        geojson:        'GEOJSON/Punta.geojson',
        startLocation:  '69.4522, 21.4514',
        endLocation:    '69.4978, 21.4321',
        parking:        '69.4975, 21.4341',
        midpoint:       '69.4925, 21.4341',
        zoomLocation:   '69.4925, 21.4341',
        mapZoom:        '11',
        mapZoomStart:   '12',
    },
    {
        municipality:   'Nordreisa',
        area:           'Reisadalen',
        name:           'Gahperus',
        route:          'Linjeveien',
        description:    'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro quidem nihil illum officiis asperiores pariatur nobis nostrum! Error quo veniam temporibus tempore quis illum saepe reprehenderit illo ratione accusamus? Expedita!',
        type:           'Enduro',
        grade:          'Advanced',
        length:         '11 km',
        climb:          '7 km',
        climbHeight:    '550m',
        geojson:        'GEOJSON/Gahperus.geojson',
        startLocation:  '69.5081, 21.3005',
        endLocation:    '69.5408, 21.3293',
        parking:        '69.5394, 21.3321',
        midpoint:       '69.5181, 21.3005',
        zoomLocation:   '69.5247, 21.3136',
        mapZoom:        '10',
        mapZoomStart:   '12',
    },
    {
        municipality:   'Nordreisa',
        area:           'Reisadalen',
        name:           'Punta',
        route:          'Puntadalen',
        description:    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro ipsum aspernatur officia, sapiente ad corporis vero vitae ducimus aut earum doloribus ab tempore odit pariatur sit illum cum dolor,<br> repudiandae voluptas, possimus veritatis ipsam exercitationem. Maiores quam mollitia nesciunt obcaecati repellendus. Molestias itaque facere fuga recusandae sint, porro dolores et?',
        type:           'XC',
        grade:          'Beginner',
        length:         '15 km',
        climb:          '15 km',
        geojson:        'GEOJSON/Punta.geojson',
        startLocation:  '69.4522, 21.4514',
        endLocation:    '69.4978, 21.4321',
        parking:        '69.4975, 21.4341',
        midpoint:       '69.4925, 21.4341',
        zoomLocation:   '69.4925, 21.4341',
        mapZoom:        '11',
        mapZoomStart:   '12',
    },
];
